name: flutterpi_tool
description: A tool to make development & distribution of flutter-pi apps easier.
version: 0.2.0
repository: https://github.com/ardera/flutterpi_tool

environment:
  sdk: ^3.0.5

executables:
  # TODO(ardera): Maybe add an alias `flutterpi-tool` here?
  flutterpi_tool: flutterpi_tool

# Add regular dependencies here.
dependencies:
  flutter_tools:
    sdk: flutter
  package_config: ^2.1.0
  github: ^9.15.0
  file: ">=6.1.4 <8.0.0"
  path: ^1.8.3
  args: ^2.4.0
  http: ^0.13.6
  meta: ^1.10.0
  process: ^4.2.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
